/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ApiEnrichRouteImport } from './routes/api/enrich'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppScanRouteImport } from './routes/_app/scan'
import { Route as AppLabelsRouteImport } from './routes/_app/labels'
import { Route as AppCaptureRouteImport } from './routes/_app/capture'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppJoinCodeRouteImport } from './routes/_app/join.$code'
import { Route as AppIIdRouteImport } from './routes/_app/i.$id'
import { Route as AppCCodeRouteImport } from './routes/_app/c.$code'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiEnrichRoute = ApiEnrichRouteImport.update({
  id: '/api/enrich',
  path: '/api/enrich',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppLabelsRoute = AppLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AppRoute,
} as any)
const AppCaptureRoute = AppCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppJoinCodeRoute = AppJoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppIIdRoute = AppIIdRouteImport.update({
  id: '/i/$id',
  path: '/i/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCCodeRoute = AppCCodeRouteImport.update({
  id: '/c/$code',
  path: '/c/$code',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/capture': typeof AppCaptureRoute
  '/labels': typeof AppLabelsRoute
  '/scan': typeof AppScanRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/api/enrich': typeof ApiEnrichRoute
  '/c/$code': typeof AppCCodeRoute
  '/i/$id': typeof AppIIdRoute
  '/join/$code': typeof AppJoinCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/capture': typeof AppCaptureRoute
  '/labels': typeof AppLabelsRoute
  '/scan': typeof AppScanRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/api/enrich': typeof ApiEnrichRoute
  '/': typeof AppIndexRoute
  '/c/$code': typeof AppCCodeRoute
  '/i/$id': typeof AppIIdRoute
  '/join/$code': typeof AppJoinCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/capture': typeof AppCaptureRoute
  '/_app/labels': typeof AppLabelsRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/enrich': typeof ApiEnrichRoute
  '/_app/': typeof AppIndexRoute
  '/_app/c/$code': typeof AppCCodeRoute
  '/_app/i/$id': typeof AppIIdRoute
  '/_app/join/$code': typeof AppJoinCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/capture'
    | '/labels'
    | '/scan'
    | '/search'
    | '/settings'
    | '/api/enrich'
    | '/c/$code'
    | '/i/$id'
    | '/join/$code'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/capture'
    | '/labels'
    | '/scan'
    | '/search'
    | '/settings'
    | '/api/enrich'
    | '/'
    | '/c/$code'
    | '/i/$id'
    | '/join/$code'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/capture'
    | '/_app/labels'
    | '/_app/scan'
    | '/_app/search'
    | '/_app/settings'
    | '/api/enrich'
    | '/_app/'
    | '/_app/c/$code'
    | '/_app/i/$id'
    | '/_app/join/$code'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiEnrichRoute: typeof ApiEnrichRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/enrich': {
      id: '/api/enrich'
      path: '/api/enrich'
      fullPath: '/api/enrich'
      preLoaderRoute: typeof ApiEnrichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/labels': {
      id: '/_app/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AppLabelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/capture': {
      id: '/_app/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof AppCaptureRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/join/$code': {
      id: '/_app/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof AppJoinCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/i/$id': {
      id: '/_app/i/$id'
      path: '/i/$id'
      fullPath: '/i/$id'
      preLoaderRoute: typeof AppIIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/c/$code': {
      id: '/_app/c/$code'
      path: '/c/$code'
      fullPath: '/c/$code'
      preLoaderRoute: typeof AppCCodeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCaptureRoute: typeof AppCaptureRoute
  AppLabelsRoute: typeof AppLabelsRoute
  AppScanRoute: typeof AppScanRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCCodeRoute: typeof AppCCodeRoute
  AppIIdRoute: typeof AppIIdRoute
  AppJoinCodeRoute: typeof AppJoinCodeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCaptureRoute: AppCaptureRoute,
  AppLabelsRoute: AppLabelsRoute,
  AppScanRoute: AppScanRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCCodeRoute: AppCCodeRoute,
  AppIIdRoute: AppIIdRoute,
  AppJoinCodeRoute: AppJoinCodeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiEnrichRoute: ApiEnrichRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
